---
name: Simone
surname: D'Ambrogio
position: "PhD"
pronouns: he/him
address: "Experimental Psychology, University of Oxford"
phone: +39 392 0995325
www: simonedambrogio.github.io
email: "simone.dambrogio@psy.ox.ac.uk"
twitter: simonedambrogio
github: simonedambrogio
linkedin: simone-d-ambrogio-abb382178/?locale=en_US
date: "`r format(Sys.time(), '%B %Y')`"
output:
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
options(tinytex.verbose = TRUE)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "PhD in Experimental Psychology", "2021-Today", "University of Oxford", "Oxford, UK",
  "Visiting Graduate Scholar, Wharton Neuroscience Initiative", "2020", "University of Pennsylvania", "Philadelphia, Pennsylvania",
  "M.Sc. in Applied Cognitive Psychology (Cum Laude)", "2017-2020", "University of Padua", "Padua, Italy",
  "Erasmus + Program", "2018", "Leiden University", "Leiden, Netherlands",
  "B.Sc. in Psychology (First class Honours)", "2017-2017", "University of Padua", "Padua, Italy",
) %>%
  detailed_entries(Degree, Year, Institution, Where)
```

# Publications

```{r}
library(dplyr)
# knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages1.bib") %>%
  arrange(desc(author$family), issued)
```
